# Generated by Django 4.2.5 on 2023-09-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_name_1", models.CharField(max_length=150)),
                (
                    "street_name_2",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("home_number", models.CharField(max_length=20)),
                ("flat_number", models.CharField(blank=True, max_length=20, null=True)),
                ("zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "country",
                    models.CharField(choices=[("PL", "POLAND")], max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                ("name", models.CharField(max_length=250)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="clubs.address",
                    ),
                ),
                ("additional_info", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Clay", "Clay"),
                            ("Synthetic Clay", "Synthetic Clay"),
                            ("Grass", "Grass"),
                            ("Synthetic Grass", "Synthetic Grass"),
                            ("Hard", "Hard"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_doubles", models.BooleanField()),
                ("is_lighting", models.BooleanField()),
                ("is_indoor", models.BooleanField()),
                ("is_winter_indoor", models.BooleanField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clubs.club"
                    ),
                ),
            ],
        ),
    ]
