# Generated by Django 4.2.5 on 2023-09-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Friendly", "Friendly"),
                            ("Training", "Training"),
                            ("League", "League"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duration", models.DurationField()),
                ("result", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clubs.court",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host",
                        to="players.player",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opponent",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Forehand Cross", "Forehand Cross"),
                            ("Forehand Line", "Forehand Line"),
                            ("Forehand Attack", "Forehand Attack"),
                            ("Forehand Volley", "Forehand Volley"),
                            ("Forehand Drop shot", "Forehand Drop shot"),
                            ("Backhand Cross", "Backhand Cross"),
                            ("Backhand Line", "Backhand Line"),
                            ("Backhand Attack", "Backhand Attack"),
                            ("Backhand Volley", "Backhand Volley"),
                            ("Backhand Drop shot", "Backhand Drop shot"),
                            ("Smatch", "Smatch"),
                            ("Service", "Service"),
                            ("Game", "Game"),
                        ],
                        max_length=100,
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "additional_info",
                    models.CharField(
                        choices=[
                            ("Forehand Cross", "Forehand Cross"),
                            ("Forehand Line", "Forehand Line"),
                            ("Forehand Attack", "Forehand Attack"),
                            ("Forehand Volley", "Forehand Volley"),
                            ("Forehand Drop shot", "Forehand Drop shot"),
                            ("Backhand Cross", "Backhand Cross"),
                            ("Backhand Line", "Backhand Line"),
                            ("Backhand Attack", "Backhand Attack"),
                            ("Backhand Volley", "Backhand Volley"),
                            ("Backhand Drop shot", "Backhand Drop shot"),
                            ("Smatch", "Smatch"),
                            ("Service", "Service"),
                            ("Game", "Game"),
                        ],
                        max_length=2000,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
        ),
    ]
