# Generated by Django 4.2.5 on 2023-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                (
                    "second_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("nick_name", models.CharField(blank=True, max_length=150)),
                (
                    "ntrp",
                    models.CharField(
                        choices=[
                            ("<2.0", "<2.0"),
                            ("2.5", "2.5"),
                            ("3.0", "3.0"),
                            ("3.5", "3.5"),
                            ("4.0", "4.0"),
                            ("4.5", "4.5"),
                            ("5.0", "5.0"),
                            (">5.0", ">5.0"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
